const mockFollowers = [
    {
        "login": "xwbash",
        "id": 45906887,
        "node_id": "MDQ6VXNlcjQ1OTA2ODg3",
        "avatar_url": "https://avatars.githubusercontent.com/u/45906887?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/xwbash",
        "html_url": "https://github.com/xwbash",
        "followers_url": "https://api.github.com/users/xwbash/followers",
        "following_url": "https://api.github.com/users/xwbash/following{/other_user}",
        "gists_url": "https://api.github.com/users/xwbash/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/xwbash/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/xwbash/subscriptions",
        "organizations_url": "https://api.github.com/users/xwbash/orgs",
        "repos_url": "https://api.github.com/users/xwbash/repos",
        "events_url": "https://api.github.com/users/xwbash/events{/privacy}",
        "received_events_url": "https://api.github.com/users/xwbash/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "rizikolik",
        "id": 46383770,
        "node_id": "MDQ6VXNlcjQ2MzgzNzcw",
        "avatar_url": "https://avatars.githubusercontent.com/u/46383770?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/rizikolik",
        "html_url": "https://github.com/rizikolik",
        "followers_url": "https://api.github.com/users/rizikolik/followers",
        "following_url": "https://api.github.com/users/rizikolik/following{/other_user}",
        "gists_url": "https://api.github.com/users/rizikolik/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/rizikolik/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/rizikolik/subscriptions",
        "organizations_url": "https://api.github.com/users/rizikolik/orgs",
        "repos_url": "https://api.github.com/users/rizikolik/repos",
        "events_url": "https://api.github.com/users/rizikolik/events{/privacy}",
        "received_events_url": "https://api.github.com/users/rizikolik/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "tokerto7001",
        "id": 75892548,
        "node_id": "MDQ6VXNlcjc1ODkyNTQ4",
        "avatar_url": "https://avatars.githubusercontent.com/u/75892548?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/tokerto7001",
        "html_url": "https://github.com/tokerto7001",
        "followers_url": "https://api.github.com/users/tokerto7001/followers",
        "following_url": "https://api.github.com/users/tokerto7001/following{/other_user}",
        "gists_url": "https://api.github.com/users/tokerto7001/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/tokerto7001/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/tokerto7001/subscriptions",
        "organizations_url": "https://api.github.com/users/tokerto7001/orgs",
        "repos_url": "https://api.github.com/users/tokerto7001/repos",
        "events_url": "https://api.github.com/users/tokerto7001/events{/privacy}",
        "received_events_url": "https://api.github.com/users/tokerto7001/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "Mr-Mesut-OZTURK",
        "id": 80154062,
        "node_id": "MDQ6VXNlcjgwMTU0MDYy",
        "avatar_url": "https://avatars.githubusercontent.com/u/80154062?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Mr-Mesut-OZTURK",
        "html_url": "https://github.com/Mr-Mesut-OZTURK",
        "followers_url": "https://api.github.com/users/Mr-Mesut-OZTURK/followers",
        "following_url": "https://api.github.com/users/Mr-Mesut-OZTURK/following{/other_user}",
        "gists_url": "https://api.github.com/users/Mr-Mesut-OZTURK/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/Mr-Mesut-OZTURK/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Mr-Mesut-OZTURK/subscriptions",
        "organizations_url": "https://api.github.com/users/Mr-Mesut-OZTURK/orgs",
        "repos_url": "https://api.github.com/users/Mr-Mesut-OZTURK/repos",
        "events_url": "https://api.github.com/users/Mr-Mesut-OZTURK/events{/privacy}",
        "received_events_url": "https://api.github.com/users/Mr-Mesut-OZTURK/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "Nonslip19",
        "id": 88439875,
        "node_id": "MDQ6VXNlcjg4NDM5ODc1",
        "avatar_url": "https://avatars.githubusercontent.com/u/88439875?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Nonslip19",
        "html_url": "https://github.com/Nonslip19",
        "followers_url": "https://api.github.com/users/Nonslip19/followers",
        "following_url": "https://api.github.com/users/Nonslip19/following{/other_user}",
        "gists_url": "https://api.github.com/users/Nonslip19/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/Nonslip19/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Nonslip19/subscriptions",
        "organizations_url": "https://api.github.com/users/Nonslip19/orgs",
        "repos_url": "https://api.github.com/users/Nonslip19/repos",
        "events_url": "https://api.github.com/users/Nonslip19/events{/privacy}",
        "received_events_url": "https://api.github.com/users/Nonslip19/received_events",
        "type": "User",
        "site_admin": false
    }
]
export default mockFollowers